### ISSUE TITLE
Шарики нельзя поймать

### ISSUE THREAD

**Issue by m-a-prod** [maxim-adaev-production/catch-the-falling-ball#1]

**Comment by m-a-prod** [comment]
В определенный момент все таки можно, есть сомнения что тот поток в котором идет проверка, очень сильно перегружен. Наверное если вынести еще в один поток все заработает, но это не факт.

**Comment by m-a-prod** [comment]
Или условие неверно

**Comment by maxim-adaev-production** [comment]
if (Mouse.onClick(MouseButton.LEFT) && circles[i][2] > Math.sqrt(Math.pow(Mouse.x() - circles[i][0], 2) + Math.pow(Mouse.y() - circles[i][1], 2)))

**Comment by m-a-prod** [comment]
`if (Mouse.onClick(MouseButton.LEFT) && circles[i][2] > Math.sqrt(Math.pow(Mouse.x() - circles[i][0], 2) + Math.pow(Mouse.y() - circles[i][1], 2))) `

**Comment by m-a-prod** [comment]
Дело было в условие я поменял onClick на hasClick, и все заработало, но теперь можно просто мышкой водить по шарикам, возможно и это исправлю.=)
